### ISSUE TITLE
Data Type Mismatch Prompt 

### ISSUE THREAD

**Issue by dawipayandas** [lugnitdgp/SQLifyHUB#2]
![data_type](https://github.com/user-attachments/assets/bbe6aae9-2dab-46c4-8a77-1068c39c1240)
### Data Type Mismatch Error Prompt

Add Feature to prompt the error message, if data type mismatch occur since it doesn't show any error message.

**Comment by Fl1s** [comment]
Assign me

**Comment by Fl1s** [comment]
Yo, @dawipayandas review my pr #8!

**Comment by Fl1s** [comment]
Can you plz mark this issue as 'hacktoberfest-accepted'?

**Comment by dawipayandas** [comment]
Sure @Fl1s, thank you for your meaningful contribution.
